version: "3.8"

services:
  # ✅ Selenium Hub (Central Manager)
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - SE_GRID_MAX_SESSION=10  # Maximum parallel test sessions
      - SE_GRID_NEW_SESSION_WAIT_TIMEOUT=30000  # Wait timeout for new sessions
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 30s
      retries: 3
      timeout: 10s
    networks:
      - selenium-grid

  # ✅ Chrome Node (Parallel Execution Enabled)
  chrome-node:
    image: selenium/node-chrome:latest
    container_name: selenium-node-chrome
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=3  # Run up to 3 tests in parallel
      - SE_NODE_MAX_SESSION=3  # Maximum sessions per node
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/status"]
      interval: 30s
      retries: 3
      timeout: 10s
    networks:
      - selenium-grid

  # ✅ Firefox Node (Parallel Execution Enabled)
  firefox-node:
    image: selenium/node-firefox:latest
    container_name: selenium-node-firefox
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=3
      - SE_NODE_MAX_SESSION=3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/status"]
      interval: 30s
      retries: 3
      timeout: 10s
    networks:
      - selenium-grid

  # ✅ Edge Node (Parallel Execution Enabled)
  edge-node:
    image: selenium/node-edge:latest
    container_name: selenium-node-edge
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=3
      - SE_NODE_MAX_SESSION=3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/status"]
      interval: 30s
      retries: 3
      timeout: 10s
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge
